"""empty message

Revision ID: 77a5e7ecb575
Revises: 76717a852bf2
Create Date: 2023-11-05 23:04:12.065392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a5e7ecb575'
down_revision = '76717a852bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make_inc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('desc', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('make_exp', schema=None) as batch_op:
        batch_op.drop_column('inc_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('make_exp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inc_type', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('make_inc')
    # ### end Alembic commands ###
